/**
 * This module contains all HTTP codes and message for easy reference and usage.
 * @module
 */

export const httpStatusCodes = {
  Continue: 100,
  SwitchingProtocols: 101,
  ProcessingDeprecated: 102,
  EarlyHints: 103,
  OK: 200,
  Created: 201,
  Accepted: 202,
  NonAuthoritativeInformation: 203,
  NoContent: 204,
  ResetContent: 205,
  PartialContent: 206,
  MultiStatus: 207,
  AlreadyReported: 208,
  IMUsed: 226,
  MultipleChoices: 300,
  MovedPermanently: 301,
  Found: 302,
  SeeOther: 303,
  NotModified: 304,
  UseProxyDeprecated: 305,
  TemporaryRedirect: 307,
  PermanentRedirect: 308,
  BadRequest: 400,
  Unauthorized: 401,
  PaymentRequired: 402,
  Forbidden: 403,
  NotFound: 404,
  MethodNotAllowed: 405,
  NotAcceptable: 406,
  ProxyAuthenticationRequired: 407,
  RequestTimeout: 408,
  Conflict: 409,
  Gone: 410,
  LengthRequired: 411,
  PreconditionFailed: 412,
  ContentTooLarge: 413,
  URITooLong: 414,
  UnsupportedMediaType: 415,
  RangeNotSatisfiable: 416,
  ExpectationFailed: 417,
  ImATeapot: 418,
  MisdirectedRequest: 421,
  UnprocessableContent: 422,
  Locked: 423,
  FailedDependency: 424,
  TooEarlyExperimental: 425,
  UpgradeRequired: 426,
  PreconditionRequired: 428,
  TooManyRequests: 429,
  RequestHeaderFieldsTooLarge: 431,
  UnavailableForLegalReasons: 451,
  InternalServerError: 500,
  NotImplemented: 501,
  BadGateway: 502,
  ServiceUnavailable: 503,
  GatewayTimeout: 504,
  HTTPVersionNotSupported: 505,
  VariantAlsoNegotiates: 506,
  InsufficientStorage: 507,
  LoopDetected: 508,
  NotExtended: 510,
  NetworkAuthenticationRequired: 511,
};

export const httpStatusMessages = {
  [httpStatusCodes.Continue]: 'Continue',
  [httpStatusCodes.SwitchingProtocols]: 'Switching Protocols',
  [httpStatusCodes.ProcessingDeprecated]: 'Processing Deprecated',
  [httpStatusCodes.EarlyHints]: 'Early Hints',
  [httpStatusCodes.OK]: 'OK',
  [httpStatusCodes.Created]: 'Created',
  [httpStatusCodes.Accepted]: 'Accepted',
  [httpStatusCodes.NonAuthoritativeInformation]:
    'Non-Authoritative Information',
  [httpStatusCodes.NoContent]: 'No Content',
  [httpStatusCodes.ResetContent]: 'Reset Content',
  [httpStatusCodes.PartialContent]: 'Partial Content',
  [httpStatusCodes.MultiStatus]: 'Multi-Status',
  [httpStatusCodes.AlreadyReported]: 'Already Reported',
  [httpStatusCodes.IMUsed]: 'IM Used',
  [httpStatusCodes.MultipleChoices]: 'Multiple Choices',
  [httpStatusCodes.MovedPermanently]: 'Moved Permanently',
  [httpStatusCodes.Found]: 'Found',
  [httpStatusCodes.SeeOther]: 'See Other',
  [httpStatusCodes.NotModified]: 'Not Modified',
  [httpStatusCodes.UseProxyDeprecated]: 'Use Proxy Deprecated',
  [httpStatusCodes.TemporaryRedirect]: 'Temporary Redirect',
  [httpStatusCodes.PermanentRedirect]: 'Permanent Redirect',
  [httpStatusCodes.BadRequest]: 'Bad Request',
  [httpStatusCodes.Unauthorized]: 'Unauthorized',
  [httpStatusCodes.PaymentRequired]: 'Payment Required',
  [httpStatusCodes.Forbidden]: 'Forbidden',
  [httpStatusCodes.NotFound]: 'Not Found',
  [httpStatusCodes.MethodNotAllowed]: 'Method Not Allowed',
  [httpStatusCodes.NotAcceptable]: 'Not Acceptable',
  [httpStatusCodes.ProxyAuthenticationRequired]:
    'Proxy Authentication Required',
  [httpStatusCodes.RequestTimeout]: 'Request Timeout',
  [httpStatusCodes.Conflict]: 'Conflict',
  [httpStatusCodes.Gone]: 'Gone',
  [httpStatusCodes.LengthRequired]: 'Length Required',
  [httpStatusCodes.PreconditionFailed]: 'Precondition Failed',
  [httpStatusCodes.ContentTooLarge]: 'Content Too Large',
  [httpStatusCodes.URITooLong]: 'URI Too Long',
  [httpStatusCodes.UnsupportedMediaType]: 'Unsupported Media Type',
  [httpStatusCodes.RangeNotSatisfiable]: 'Range Not Satisfiable',
  [httpStatusCodes.ExpectationFailed]: 'Expectation Failed',
  [httpStatusCodes.ImATeapot]: "I'm a teapot",
  [httpStatusCodes.MisdirectedRequest]: 'Misdirected Request',
  [httpStatusCodes.UnprocessableContent]: 'Unprocessable Content',
  [httpStatusCodes.Locked]: 'Locked',
  [httpStatusCodes.FailedDependency]: 'Failed Dependency',
  [httpStatusCodes.TooEarlyExperimental]: 'Too Early Experimental',
  [httpStatusCodes.UpgradeRequired]: 'Upgrade Required',
  [httpStatusCodes.PreconditionRequired]: 'Precondition Required',
  [httpStatusCodes.TooManyRequests]: 'Too Many Requests',
  [httpStatusCodes.RequestHeaderFieldsTooLarge]:
    'Request Header Fields Too Large',
  [httpStatusCodes.UnavailableForLegalReasons]: 'Unavailable For Legal Reasons',
  [httpStatusCodes.InternalServerError]: 'Internal Server Error',
  [httpStatusCodes.NotImplemented]: 'Not Implemented',
  [httpStatusCodes.BadGateway]: 'Bad Gateway',
  [httpStatusCodes.ServiceUnavailable]: 'Service Unavailable',
  [httpStatusCodes.GatewayTimeout]: 'Gateway Timeout',
  [httpStatusCodes.HTTPVersionNotSupported]: 'HTTP Version Not Supported',
  [httpStatusCodes.VariantAlsoNegotiates]: 'Variant Also Negotiates',
  [httpStatusCodes.InsufficientStorage]: 'Insufficient Storage',
  [httpStatusCodes.LoopDetected]: 'Loop Detected',
  [httpStatusCodes.NotExtended]: 'Not Extended',
  [httpStatusCodes.NetworkAuthenticationRequired]:
    'Network Authentication Required',
};
